version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:
  front:
    build:
      context: .
      dockerfile: DockerfileDev
    command: >
      sh -c "yarn serve"
    working_dir: /app
    volumes:
      - ./:/app/
    environment:
      NODE_ENV: development.local
      VUE_APP_API_HOST: ${VUE_APP_API_HOST}
      VUE_APP_PUBLIC_PATH: ${VUE_APP_PUBLIC_PATH}
    logging: *default-logging
    ports:
      - 8088:8080
