# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CICD

on:
  push:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16
      - name: deploy prod
        if: contains(github.ref, 'master')
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: root@${{ secrets.DIGITAL_OCEAN_HOST }}
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            SERVICES=$(docker service ls --filter name=story-maker-editor_sm-editor --quiet | wc -l)
            if [[ "$SERVICES" -eq 0 ]]; then
                docker service create \
                        --name story-maker-editor_sm-editor \
                        --network vac-network-traefik \
                        -l traefik.enable=true \
                        -l traefik.docker.network=vac-network-traefik \
                        -l traefik.http.routers.sm-editor.entrypoints=websecure \
                        -l 'traefik.http.routers.sm-editor.rule=Host(`jrojaspin.com.ar`) and PathPrefix(`/story-maker/editor`)' \
                        -l traefik.http.routers.sm-editor.tls=true \
                        -l traefik.http.services.sm-editor.loadbalancer.server.port=80 \
                        jotaram/sm-editor:latest
            fi
            docker service update --image jotaram/sm-editor:latest story-maker-editor_sm-editor
