# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CICD

on:
  push:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16
      - name: upload image to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.VAC_DOCKER_USER }}
          password: ${{ secrets.VAC_DOCKER_PASSWORD }}
          repository: jotaram/sm-editor
          tag_with_ref: true
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: root
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.DIGITAL_OCEAN_HOST }}
      - name: copy configuration
        run: scp docker-compose-traefik.yml staging:/tmp/docker-compose-traefik-historymaker-editor.yml
      - name: update image
        run: ssh staging 'docker pull jotaram/sm-editor:latest'
      - name: rm stack
        run: ssh staging 'docker stack rm historymaker-editor'
      - name: up stack
        run: ssh staging 'docker stack deploy --with-registry-auth --compose-file /tmp/docker-compose-traefik-historymaker-editor.yml historymaker-editor'
